const FLAGS = {
    SEARCH: {
        FILTER: 'FILTER',
        NEW_KNOWLEDGE: 'NEW_KNOWLEDGE',
        CHANGE_VOTE_MODAL_STATUS: 'CHANGE_VOTE_MODAL_STATUS',
        CHANGE_ADD_MODAL_STATUS: 'CHANGE_ADD_MODAL_STATUS',
        REMOVE_KNOWLEDGE: 'REMOVE_KNOWLEDGE',
    },
    BLOCK: {
        ADD_KNOWLEDGE_TO_VOTE_SUCCESS: 'ADD_KNOWLEDGE_TO_VOTE_SUCCESS',
        NEW_BLOCK_SUCCESS: 'NEW_BLOCK_SUCCESS',
        NEW_BLOCK_BEGIN: 'NEW_BLOCK_BEGIN',
        END_VOTE: 'END_VOTE',
        PASS_TIME: 'PASS_TIME',
        VOTE: 'VOTE',
        UPDATE_BLOCK: 'UPDATE_BLOCK',
    },
    FETCH_BLOCKS_BEGIN: 'FETCH_BLOCKS_BEGIN',
    FETCH_BLOCKS_SUCCESS: 'FETCH_BLOCKS_SUCCESS',
    FETCH_BLOCKS_FAILURE: 'FETCH_BLOCKS_FAILURE',
};

export default FLAGS;
